# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.12"                                                                                                                                                                                              

# Instalação de Módulos que são necessários para a Aplicação.                                                                                                                                            
install:                                                                                                                                                                                                 
  - pip install flask                                                                                                                                                                                    

# Defini o script de Teste que deve rodar toda vez que o código for alterado.                                                                                                                            
script:                                                                                                                                                                                                  
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devsecopssre-paulo
  on:
    all_branches: true